name: ⚠ Bug report
description: Create a bug/issue report
title: '[Bug]: '
labels: ['Bug']
body:
  - type: textarea
    id: description
    attributes:
      label: Describe the bug
      description: A clear description of what the bug and/or issue is.
    validations:
      required: true
  - type: input
    id: reframework-version
    attributes:
      label: REFramework Version
      description: What version of REFramework are you using?
      placeholder: e.g., 01208
    validations:
      required: true
  - type: input
    id: buffer-version
    attributes:
      label: Buffer Version
      description: What version of Buffer are you using?
      placeholder: e.g., 1.0.0
    validations:
      required: true
  - type: textarea
    id: context
    attributes:
      label: Additional context
      description: Add any other context about the problem here
  - type: markdown
    attributes:
      value: >-
        ---

        <br>


        > __Note:__ Make sure to add any screenshots or images that will help
        explain or show the issue to additional context.
